config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  resource :breaths, only: :create

  get 'meditate/index'
  get '/meditate' => 'meditate#index'
  get '/meditate/intro' => 'meditate#intro'
  post '/meditate/set_cycle' => 'meditate#set_cycle'
  get '/breaths/show_record' => 'breaths#show_record'

end

app/models/breath.rb
class Breath < ActiveRecord::Base
  def self.createFromParams(params)
    b = Breath.new
    b.attributes = { longestInhale: params[:longestInhale], longestExhale: params[:longestExhale], longestAverageInhale: params[:averageInhale], longestAverageExhale: params[:averageExhale] }
    b.save
    b
  end

  def self.longestInhale
    Breath.order(longestInhale: :desc).limit(1).first.longestInhale
  end

  def self.longestExhale
    Breath.order(longestExhale: :desc).limit(1).first.longestExhale
  end

  def self.longestAverageInhale
    Breath.order(longestAverageInhale: :desc).limit(1).first.longestAverageInhale
  end

  def self.longestAverageExhale
    Breath.order(longestAverageExhale: :desc).limit(1).first.longestAverageExhale
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/breaths_controller.rb
class BreathsController < ApplicationController
  def create
    Breath.createFromParams(params[:record])
    render json: record
  end

  def show_record
    render json: record
  end

  private

    def record
      {
        longestInhale: Breath.longestInhale,
        longestExhale: Breath.longestExhale,
        longestAverageInhale: Breath.longestAverageInhale,
        longestAverageExhale: Breath.longestAverageExhale
      }
    end
end

app/controllers/meditate_controller.rb
class MeditateController < ApplicationController
  def index
  end

  def intro
  end

  def set_cycle
    session[:cycles] = params[:cycle]
    redirect_to :meditate_index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breaths_helper.rb
module BreathsHelper
end

app/views/breaths/create.html.erb
<h1>Breaths#create</h1>
<p>Find me in app/views/breaths/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MeditationTrainer</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/meditate/index.html.erb
<script type="text/javascript" charset="utf-8">
  var MAX_BREATH_CYCLES = parseInt("<%= session[:cycles] || 3 %>");
</script>

<section id="meditation-application">
  <section id="prompt-view">
    <h1>Prompt text</h1>
  </section>
  <section id="stats-view">
    <table>
      <tr>
        <th>Statistic</th>
        <th>Value</th>
      </tr>
      <tr>
        <td>Longest Inhale Duration</td>
        <td id='longest-inhale-duration'>&nbsp;</td>
      </tr>
      <tr>
        <td>Average Inhale Duration</td>
        <td id='average-inhale-duration'>&nbsp;</td>
      </tr>
      <tr>
        <td>Longest Exhale Duration</td>
        <td id='longest-exhale-duration'>&nbsp;</td>
      </tr>
      <tr>
        <td>Average Exhale Duration</td>
        <td id='average-exhale-duration'>&nbsp;</td>
      </tr>
      <tr>
        <td>Longest Cycle Duration</td>
        <td id='longest-cycle-duration'>&nbsp;</td>
      </tr>
      <tr>
        <td>Average Inhale Duration</td>
        <td id='average-cycle-duration'>&nbsp;</td>
      </tr>
    </table>
    <table>
      <tr>
        <td>Longest Inhale Ever</td>
        <td id='longest-inhale-duration-ever'>&nbsp;</td>
      </tr>
      <tr>
        <td>Longest Average Inhale Duration Ever</td>
        <td id='average-inhale-duration-ever'>&nbsp;</td>
      </tr>
      <tr>
        <td>Longest Exhale Ever</td>
        <td id='longest-exhale-duration-ever'>&nbsp;</td>
      </tr>
      <tr>
        <td>Longest Average Exhale Duration Ever</td>
        <td id='average-exhale-duration-ever'>&nbsp;</td>
      </tr>
    </table>
  </section>
  <section id="timer-view">
    <p><%= image_tag 'flo_dogg.jpg' %></p>
  </section>
</section>

app/views/meditate/intro.html.erb
<%= form_tag  meditate_set_cycle_path do%>
  <%= label_tag :cycle, "Number of breaths to meditate for" %>
  <%= text_field_tag :cycle %>
  <%= submit_tag "Meditate" %>
<% end %>